[versions]
ajalt-mordant = "3.0.1"
kotlin = "2.1.0"
buildconfig = "5.3.1"
buildParameters = "1.4.4"
dependencyAnalysis = "2.6.1"
jakeWharton-picnic = "0.7.0"
kotlinx-serialization = "1.8.0"
kotlinx-coroutines = "1.10.1"
rickBusarow-doks = "0.2.0"
rickBusarow-kase = "0.11.1"
rickBusarow-kgx = "0.1.12"
rickBusarow-ktlint = "0.2.2"
rickBusarow-ktrules = "1.4.0"
rickBusarow-moduleCheck = "0.12.5"

[plugins]
buildParameters = { id = "org.gradlex.build-parameters", version.ref = "buildParameters" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "com.rickbusarow.ktlint", version.ref = "rickBusarow-ktlint" }
moduleCheck = { id = "com.rickbusarow.module-check", version.ref = "rickBusarow-moduleCheck" }

[libraries]

ajalt-mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "ajalt-mordant" }
ajalt-mordant-coroutines = { module = "com.github.ajalt.mordant:mordant-coroutines", version.ref = "ajalt-mordant" }

buildconfig = { module = "com.github.gmazzo:gradle-buildconfig-plugin", version.ref = "buildconfig" }

jakeWharton-picnic = { module = "com.jakewharton.picnic:picnic", version.ref = "jakeWharton-picnic" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

rickBusarow-doks = { module = "com.rickbusarow.doks:doks-gradle-plugin", version.ref = "rickBusarow-doks" }
rickBusarow-kase = { module = "com.rickbusarow.kase:kase", version.ref = "rickBusarow-kase" }
rickBusarow-kase-gradle = { module = "com.rickbusarow.kase:kase-gradle", version.ref = "rickBusarow-kase" }
rickBusarow-kase-gradle-dsl = { module = "com.rickbusarow.kase:kase-gradle-dsl", version.ref = "rickBusarow-kase" }
rickBusarow-kgx-names = { module = "com.rickbusarow.kgx:names", version.ref = "rickBusarow-kgx" }
rickBusarow-kgx = { module = "com.rickbusarow.kgx:kotlin-gradle-extensions", version.ref = "rickBusarow-kgx" }
rickBusarow-ktlint = { module = "com.rickbusarow.ktlint:ktlint-gradle-plugin", version.ref = "rickBusarow-ktlint" }
rickBusarow-ktrules = { module = "com.rickbusarow.ktrules:ktrules", version.ref = "rickBusarow-ktrules" }
rickBusarow-moduleCheck-gradle-plugin = { module = "com.rickbusarow.modulecheck:plugin", version.ref = "rickBusarow-moduleCheck" }
